# Generated by Django 4.2.2 on 2023-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarynotes',
            name='author',
            field=models.CharField(default='anon', max_length=30),
        ),
    ]
