# Generated by Django 4.2.2 on 2023-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarynotes', '0002_summarynotes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarynotes',
            name='author',
            field=models.CharField(default='ANONYMOUS', max_length=30),
        ),
    ]
